import axios from "axios";
import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import UserCard from "../components/UserCard";
import { retrieveAll } from "../db";

export interface IUser {
  id: number;
  name: string;
  role: "Admin" | "User";
}

interface IIndexProps {
  users: Array<IUser>;
}

const Index: NextPage<IIndexProps> = ({ users }) => {
  const router = useRouter();

  const handleDeleteUser = (id: number) => {
    axios.post("/api/delete", { id }).then(() => router.reload());
  };

  return (
    <div>
      <Head>
        <title>Esteban&apos;s Next Playground</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section>
        <h1 className="text-2xl">List of users</h1>
        <div className="mx-20 mt-10">
          {users.map((user) => (
            <UserCard
              user={user}
              key={user.id}
              handleDeleteUser={handleDeleteUser}
            />
          ))}
        </div>
      </section>
    </div>
  );
};

export default Index;

// SSG
export async function getStaticProps() {
  const users = retrieveAll();
  return {
    props: { users },
    revalidate: 5,
  };
}

// SSR
// export async function getServerSideProps() {
//   await new Promise((resolve) => setTimeout(resolve, 3000));
//   return {
//     props: { users: USERS },
//   };
// }
